package com.konfigthis.client;

import com.konfigthis.client.api.AnnouncementBannerApi;
import com.konfigthis.client.api.AppDataPoliciesEapApi;
import com.konfigthis.client.api.AppMigrationApi;
import com.konfigthis.client.api.AppPropertiesApi;
import com.konfigthis.client.api.ApplicationRolesApi;
import com.konfigthis.client.api.AuditRecordsApi;
import com.konfigthis.client.api.AvatarsApi;
import com.konfigthis.client.api.ClassificationLevelsApi;
import com.konfigthis.client.api.DashboardsApi;
import com.konfigthis.client.api.DynamicModulesApi;
import com.konfigthis.client.api.FilterSharingApi;
import com.konfigthis.client.api.FiltersApi;
import com.konfigthis.client.api.GroupAndUserPickerApi;
import com.konfigthis.client.api.GroupsApi;
import com.konfigthis.client.api.IssueAttachmentsApi;
import com.konfigthis.client.api.IssueCommentPropertiesApi;
import com.konfigthis.client.api.IssueCommentsApi;
import com.konfigthis.client.api.IssueCustomFieldConfigurationAppsApi;
import com.konfigthis.client.api.IssueCustomFieldContextsApi;
import com.konfigthis.client.api.IssueCustomFieldOptionsApi;
import com.konfigthis.client.api.IssueCustomFieldOptionsAppsApi;
import com.konfigthis.client.api.IssueCustomFieldValuesAppsApi;
import com.konfigthis.client.api.IssueFieldConfigurationsApi;
import com.konfigthis.client.api.IssueFieldsApi;
import com.konfigthis.client.api.IssueLinkTypesApi;
import com.konfigthis.client.api.IssueLinksApi;
import com.konfigthis.client.api.IssueNavigatorSettingsApi;
import com.konfigthis.client.api.IssueNotificationSchemesApi;
import com.konfigthis.client.api.IssuePrioritiesApi;
import com.konfigthis.client.api.IssuePropertiesApi;
import com.konfigthis.client.api.IssueRemoteLinksApi;
import com.konfigthis.client.api.IssueResolutionsApi;
import com.konfigthis.client.api.IssueSearchApi;
import com.konfigthis.client.api.IssueSecurityLevelApi;
import com.konfigthis.client.api.IssueSecuritySchemesApi;
import com.konfigthis.client.api.IssueTypePropertiesApi;
import com.konfigthis.client.api.IssueTypeSchemesApi;
import com.konfigthis.client.api.IssueTypeScreenSchemesApi;
import com.konfigthis.client.api.IssueTypesApi;
import com.konfigthis.client.api.IssueVotesApi;
import com.konfigthis.client.api.IssueWatchersApi;
import com.konfigthis.client.api.IssueWorklogPropertiesApi;
import com.konfigthis.client.api.IssueWorklogsApi;
import com.konfigthis.client.api.IssuesApi;
import com.konfigthis.client.api.JqlApi;
import com.konfigthis.client.api.JqlFunctionsAppsApi;
import com.konfigthis.client.api.JiraExpressionsApi;
import com.konfigthis.client.api.JiraSettingsApi;
import com.konfigthis.client.api.LabelsApi;
import com.konfigthis.client.api.LicenseMetricsApi;
import com.konfigthis.client.api.MyselfApi;
import com.konfigthis.client.api.PermissionSchemesApi;
import com.konfigthis.client.api.PermissionsApi;
import com.konfigthis.client.api.ProjectAvatarsApi;
import com.konfigthis.client.api.ProjectCategoriesApi;
import com.konfigthis.client.api.ProjectClassificationLevelsApi;
import com.konfigthis.client.api.ProjectComponentsApi;
import com.konfigthis.client.api.ProjectEmailApi;
import com.konfigthis.client.api.ProjectFeaturesApi;
import com.konfigthis.client.api.ProjectKeyAndNameValidationApi;
import com.konfigthis.client.api.ProjectPermissionSchemesApi;
import com.konfigthis.client.api.ProjectPropertiesApi;
import com.konfigthis.client.api.ProjectRoleActorsApi;
import com.konfigthis.client.api.ProjectRolesApi;
import com.konfigthis.client.api.ProjectTypesApi;
import com.konfigthis.client.api.ProjectVersionsApi;
import com.konfigthis.client.api.ProjectsApi;
import com.konfigthis.client.api.ScreenSchemesApi;
import com.konfigthis.client.api.ScreenTabFieldsApi;
import com.konfigthis.client.api.ScreenTabsApi;
import com.konfigthis.client.api.ScreensApi;
import com.konfigthis.client.api.ServerInfoApi;
import com.konfigthis.client.api.ServiceRegistryApi;
import com.konfigthis.client.api.StatusApi;
import com.konfigthis.client.api.TasksApi;
import com.konfigthis.client.api.TimeTrackingApi;
import com.konfigthis.client.api.UiModificationsAppsApi;
import com.konfigthis.client.api.UserPropertiesApi;
import com.konfigthis.client.api.UserSearchApi;
import com.konfigthis.client.api.UsersApi;
import com.konfigthis.client.api.WebhooksApi;
import com.konfigthis.client.api.WorkflowSchemeDraftsApi;
import com.konfigthis.client.api.WorkflowSchemeProjectAssociationsApi;
import com.konfigthis.client.api.WorkflowSchemesApi;
import com.konfigthis.client.api.WorkflowStatusCategoriesApi;
import com.konfigthis.client.api.WorkflowStatusesApi;
import com.konfigthis.client.api.WorkflowTransitionPropertiesApi;
import com.konfigthis.client.api.WorkflowTransitionRulesApi;
import com.konfigthis.client.api.WorkflowsApi;

public class AtlassianJira {
    private ApiClient apiClient;
    public final AnnouncementBannerApi announcementBanner;
    public final AppDataPoliciesEapApi appDataPoliciesEap;
    public final AppMigrationApi appMigration;
    public final AppPropertiesApi appProperties;
    public final ApplicationRolesApi applicationRoles;
    public final AuditRecordsApi auditRecords;
    public final AvatarsApi avatars;
    public final ClassificationLevelsApi classificationLevels;
    public final DashboardsApi dashboards;
    public final DynamicModulesApi dynamicModules;
    public final FilterSharingApi filterSharing;
    public final FiltersApi filters;
    public final GroupAndUserPickerApi groupAndUserPicker;
    public final GroupsApi groups;
    public final IssueAttachmentsApi issueAttachments;
    public final IssueCommentPropertiesApi issueCommentProperties;
    public final IssueCommentsApi issueComments;
    public final IssueCustomFieldConfigurationAppsApi issueCustomFieldConfigurationApps;
    public final IssueCustomFieldContextsApi issueCustomFieldContexts;
    public final IssueCustomFieldOptionsApi issueCustomFieldOptions;
    public final IssueCustomFieldOptionsAppsApi issueCustomFieldOptionsApps;
    public final IssueCustomFieldValuesAppsApi issueCustomFieldValuesApps;
    public final IssueFieldConfigurationsApi issueFieldConfigurations;
    public final IssueFieldsApi issueFields;
    public final IssueLinkTypesApi issueLinkTypes;
    public final IssueLinksApi issueLinks;
    public final IssueNavigatorSettingsApi issueNavigatorSettings;
    public final IssueNotificationSchemesApi issueNotificationSchemes;
    public final IssuePrioritiesApi issuePriorities;
    public final IssuePropertiesApi issueProperties;
    public final IssueRemoteLinksApi issueRemoteLinks;
    public final IssueResolutionsApi issueResolutions;
    public final IssueSearchApi issueSearch;
    public final IssueSecurityLevelApi issueSecurityLevel;
    public final IssueSecuritySchemesApi issueSecuritySchemes;
    public final IssueTypePropertiesApi issueTypeProperties;
    public final IssueTypeSchemesApi issueTypeSchemes;
    public final IssueTypeScreenSchemesApi issueTypeScreenSchemes;
    public final IssueTypesApi issueTypes;
    public final IssueVotesApi issueVotes;
    public final IssueWatchersApi issueWatchers;
    public final IssueWorklogPropertiesApi issueWorklogProperties;
    public final IssueWorklogsApi issueWorklogs;
    public final IssuesApi issues;
    public final JqlApi jql;
    public final JqlFunctionsAppsApi jqlFunctionsApps;
    public final JiraExpressionsApi jiraExpressions;
    public final JiraSettingsApi jiraSettings;
    public final LabelsApi labels;
    public final LicenseMetricsApi licenseMetrics;
    public final MyselfApi myself;
    public final PermissionSchemesApi permissionSchemes;
    public final PermissionsApi permissions;
    public final ProjectAvatarsApi projectAvatars;
    public final ProjectCategoriesApi projectCategories;
    public final ProjectClassificationLevelsApi projectClassificationLevels;
    public final ProjectComponentsApi projectComponents;
    public final ProjectEmailApi projectEmail;
    public final ProjectFeaturesApi projectFeatures;
    public final ProjectKeyAndNameValidationApi projectKeyAndNameValidation;
    public final ProjectPermissionSchemesApi projectPermissionSchemes;
    public final ProjectPropertiesApi projectProperties;
    public final ProjectRoleActorsApi projectRoleActors;
    public final ProjectRolesApi projectRoles;
    public final ProjectTypesApi projectTypes;
    public final ProjectVersionsApi projectVersions;
    public final ProjectsApi projects;
    public final ScreenSchemesApi screenSchemes;
    public final ScreenTabFieldsApi screenTabFields;
    public final ScreenTabsApi screenTabs;
    public final ScreensApi screens;
    public final ServerInfoApi serverInfo;
    public final ServiceRegistryApi serviceRegistry;
    public final StatusApi status;
    public final TasksApi tasks;
    public final TimeTrackingApi timeTracking;
    public final UiModificationsAppsApi uiModificationsApps;
    public final UserPropertiesApi userProperties;
    public final UserSearchApi userSearch;
    public final UsersApi users;
    public final WebhooksApi webhooks;
    public final WorkflowSchemeDraftsApi workflowSchemeDrafts;
    public final WorkflowSchemeProjectAssociationsApi workflowSchemeProjectAssociations;
    public final WorkflowSchemesApi workflowSchemes;
    public final WorkflowStatusCategoriesApi workflowStatusCategories;
    public final WorkflowStatusesApi workflowStatuses;
    public final WorkflowTransitionPropertiesApi workflowTransitionProperties;
    public final WorkflowTransitionRulesApi workflowTransitionRules;
    public final WorkflowsApi workflows;

    public AtlassianJira() {
        this(null);
    }

    public AtlassianJira(Configuration configuration) {
        this.apiClient = new ApiClient(null, configuration);
        this.announcementBanner = new AnnouncementBannerApi(this.apiClient);
        this.appDataPoliciesEap = new AppDataPoliciesEapApi(this.apiClient);
        this.appMigration = new AppMigrationApi(this.apiClient);
        this.appProperties = new AppPropertiesApi(this.apiClient);
        this.applicationRoles = new ApplicationRolesApi(this.apiClient);
        this.auditRecords = new AuditRecordsApi(this.apiClient);
        this.avatars = new AvatarsApi(this.apiClient);
        this.classificationLevels = new ClassificationLevelsApi(this.apiClient);
        this.dashboards = new DashboardsApi(this.apiClient);
        this.dynamicModules = new DynamicModulesApi(this.apiClient);
        this.filterSharing = new FilterSharingApi(this.apiClient);
        this.filters = new FiltersApi(this.apiClient);
        this.groupAndUserPicker = new GroupAndUserPickerApi(this.apiClient);
        this.groups = new GroupsApi(this.apiClient);
        this.issueAttachments = new IssueAttachmentsApi(this.apiClient);
        this.issueCommentProperties = new IssueCommentPropertiesApi(this.apiClient);
        this.issueComments = new IssueCommentsApi(this.apiClient);
        this.issueCustomFieldConfigurationApps = new IssueCustomFieldConfigurationAppsApi(this.apiClient);
        this.issueCustomFieldContexts = new IssueCustomFieldContextsApi(this.apiClient);
        this.issueCustomFieldOptions = new IssueCustomFieldOptionsApi(this.apiClient);
        this.issueCustomFieldOptionsApps = new IssueCustomFieldOptionsAppsApi(this.apiClient);
        this.issueCustomFieldValuesApps = new IssueCustomFieldValuesAppsApi(this.apiClient);
        this.issueFieldConfigurations = new IssueFieldConfigurationsApi(this.apiClient);
        this.issueFields = new IssueFieldsApi(this.apiClient);
        this.issueLinkTypes = new IssueLinkTypesApi(this.apiClient);
        this.issueLinks = new IssueLinksApi(this.apiClient);
        this.issueNavigatorSettings = new IssueNavigatorSettingsApi(this.apiClient);
        this.issueNotificationSchemes = new IssueNotificationSchemesApi(this.apiClient);
        this.issuePriorities = new IssuePrioritiesApi(this.apiClient);
        this.issueProperties = new IssuePropertiesApi(this.apiClient);
        this.issueRemoteLinks = new IssueRemoteLinksApi(this.apiClient);
        this.issueResolutions = new IssueResolutionsApi(this.apiClient);
        this.issueSearch = new IssueSearchApi(this.apiClient);
        this.issueSecurityLevel = new IssueSecurityLevelApi(this.apiClient);
        this.issueSecuritySchemes = new IssueSecuritySchemesApi(this.apiClient);
        this.issueTypeProperties = new IssueTypePropertiesApi(this.apiClient);
        this.issueTypeSchemes = new IssueTypeSchemesApi(this.apiClient);
        this.issueTypeScreenSchemes = new IssueTypeScreenSchemesApi(this.apiClient);
        this.issueTypes = new IssueTypesApi(this.apiClient);
        this.issueVotes = new IssueVotesApi(this.apiClient);
        this.issueWatchers = new IssueWatchersApi(this.apiClient);
        this.issueWorklogProperties = new IssueWorklogPropertiesApi(this.apiClient);
        this.issueWorklogs = new IssueWorklogsApi(this.apiClient);
        this.issues = new IssuesApi(this.apiClient);
        this.jql = new JqlApi(this.apiClient);
        this.jqlFunctionsApps = new JqlFunctionsAppsApi(this.apiClient);
        this.jiraExpressions = new JiraExpressionsApi(this.apiClient);
        this.jiraSettings = new JiraSettingsApi(this.apiClient);
        this.labels = new LabelsApi(this.apiClient);
        this.licenseMetrics = new LicenseMetricsApi(this.apiClient);
        this.myself = new MyselfApi(this.apiClient);
        this.permissionSchemes = new PermissionSchemesApi(this.apiClient);
        this.permissions = new PermissionsApi(this.apiClient);
        this.projectAvatars = new ProjectAvatarsApi(this.apiClient);
        this.projectCategories = new ProjectCategoriesApi(this.apiClient);
        this.projectClassificationLevels = new ProjectClassificationLevelsApi(this.apiClient);
        this.projectComponents = new ProjectComponentsApi(this.apiClient);
        this.projectEmail = new ProjectEmailApi(this.apiClient);
        this.projectFeatures = new ProjectFeaturesApi(this.apiClient);
        this.projectKeyAndNameValidation = new ProjectKeyAndNameValidationApi(this.apiClient);
        this.projectPermissionSchemes = new ProjectPermissionSchemesApi(this.apiClient);
        this.projectProperties = new ProjectPropertiesApi(this.apiClient);
        this.projectRoleActors = new ProjectRoleActorsApi(this.apiClient);
        this.projectRoles = new ProjectRolesApi(this.apiClient);
        this.projectTypes = new ProjectTypesApi(this.apiClient);
        this.projectVersions = new ProjectVersionsApi(this.apiClient);
        this.projects = new ProjectsApi(this.apiClient);
        this.screenSchemes = new ScreenSchemesApi(this.apiClient);
        this.screenTabFields = new ScreenTabFieldsApi(this.apiClient);
        this.screenTabs = new ScreenTabsApi(this.apiClient);
        this.screens = new ScreensApi(this.apiClient);
        this.serverInfo = new ServerInfoApi(this.apiClient);
        this.serviceRegistry = new ServiceRegistryApi(this.apiClient);
        this.status = new StatusApi(this.apiClient);
        this.tasks = new TasksApi(this.apiClient);
        this.timeTracking = new TimeTrackingApi(this.apiClient);
        this.uiModificationsApps = new UiModificationsAppsApi(this.apiClient);
        this.userProperties = new UserPropertiesApi(this.apiClient);
        this.userSearch = new UserSearchApi(this.apiClient);
        this.users = new UsersApi(this.apiClient);
        this.webhooks = new WebhooksApi(this.apiClient);
        this.workflowSchemeDrafts = new WorkflowSchemeDraftsApi(this.apiClient);
        this.workflowSchemeProjectAssociations = new WorkflowSchemeProjectAssociationsApi(this.apiClient);
        this.workflowSchemes = new WorkflowSchemesApi(this.apiClient);
        this.workflowStatusCategories = new WorkflowStatusCategoriesApi(this.apiClient);
        this.workflowStatuses = new WorkflowStatusesApi(this.apiClient);
        this.workflowTransitionProperties = new WorkflowTransitionPropertiesApi(this.apiClient);
        this.workflowTransitionRules = new WorkflowTransitionRulesApi(this.apiClient);
        this.workflows = new WorkflowsApi(this.apiClient);
    }

}
