/*
 * The Jira Cloud platform REST API
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT-9aad01a33a3dae75a5b6aedf98c77d2cbd2f865d
 * Contact: ecosystem@atlassian.com
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for FieldReferenceData
 */
public class FieldReferenceDataTest {
    private final FieldReferenceData model = new FieldReferenceData();

    /**
     * Model tests for FieldReferenceData
     */
    @Test
    public void testFieldReferenceData() {
        // TODO: test FieldReferenceData
    }

    /**
     * Test the property 'auto'
     */
    @Test
    public void autoTest() {
        // TODO: test auto
    }

    /**
     * Test the property 'cfid'
     */
    @Test
    public void cfidTest() {
        // TODO: test cfid
    }

    /**
     * Test the property 'deprecated'
     */
    @Test
    public void deprecatedTest() {
        // TODO: test deprecated
    }

    /**
     * Test the property 'deprecatedSearcherKey'
     */
    @Test
    public void deprecatedSearcherKeyTest() {
        // TODO: test deprecatedSearcherKey
    }

    /**
     * Test the property 'displayName'
     */
    @Test
    public void displayNameTest() {
        // TODO: test displayName
    }

    /**
     * Test the property 'operators'
     */
    @Test
    public void operatorsTest() {
        // TODO: test operators
    }

    /**
     * Test the property 'orderable'
     */
    @Test
    public void orderableTest() {
        // TODO: test orderable
    }

    /**
     * Test the property 'searchable'
     */
    @Test
    public void searchableTest() {
        // TODO: test searchable
    }

    /**
     * Test the property 'types'
     */
    @Test
    public void typesTest() {
        // TODO: test types
    }

    /**
     * Test the property 'value'
     */
    @Test
    public void valueTest() {
        // TODO: test value
    }

}
