/*
 * The Jira Cloud platform REST API
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT-9aad01a33a3dae75a5b6aedf98c77d2cbd2f865d
 * Contact: ecosystem@atlassian.com
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.FieldMetadata;
import com.konfigthis.client.model.Scope;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.HashMap;
import java.util.Map;
import java.util.UUID;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for IssueTypeIssueCreateMetadata
 */
public class IssueTypeIssueCreateMetadataTest {
    private final IssueTypeIssueCreateMetadata model = new IssueTypeIssueCreateMetadata();

    /**
     * Model tests for IssueTypeIssueCreateMetadata
     */
    @Test
    public void testIssueTypeIssueCreateMetadata() {
        // TODO: test IssueTypeIssueCreateMetadata
    }

    /**
     * Test the property 'description'
     */
    @Test
    public void descriptionTest() {
        // TODO: test description
    }

    /**
     * Test the property 'avatarId'
     */
    @Test
    public void avatarIdTest() {
        // TODO: test avatarId
    }

    /**
     * Test the property 'entityId'
     */
    @Test
    public void entityIdTest() {
        // TODO: test entityId
    }

    /**
     * Test the property 'expand'
     */
    @Test
    public void expandTest() {
        // TODO: test expand
    }

    /**
     * Test the property 'fields'
     */
    @Test
    public void fieldsTest() {
        // TODO: test fields
    }

    /**
     * Test the property 'hierarchyLevel'
     */
    @Test
    public void hierarchyLevelTest() {
        // TODO: test hierarchyLevel
    }

    /**
     * Test the property 'iconUrl'
     */
    @Test
    public void iconUrlTest() {
        // TODO: test iconUrl
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'scope'
     */
    @Test
    public void scopeTest() {
        // TODO: test scope
    }

    /**
     * Test the property 'self'
     */
    @Test
    public void selfTest() {
        // TODO: test self
    }

    /**
     * Test the property 'subtask'
     */
    @Test
    public void subtaskTest() {
        // TODO: test subtask
    }

}
