/*
 * The Jira Cloud platform REST API
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT-9aad01a33a3dae75a5b6aedf98c77d2cbd2f865d
 * Contact: ecosystem@atlassian.com
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.ErrorCollection;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for SanitizedJqlQuery
 */
public class SanitizedJqlQueryTest {
    private final SanitizedJqlQuery model = new SanitizedJqlQuery();

    /**
     * Model tests for SanitizedJqlQuery
     */
    @Test
    public void testSanitizedJqlQuery() {
        // TODO: test SanitizedJqlQuery
    }

    /**
     * Test the property 'accountId'
     */
    @Test
    public void accountIdTest() {
        // TODO: test accountId
    }

    /**
     * Test the property 'errors'
     */
    @Test
    public void errorsTest() {
        // TODO: test errors
    }

    /**
     * Test the property 'initialQuery'
     */
    @Test
    public void initialQueryTest() {
        // TODO: test initialQuery
    }

    /**
     * Test the property 'sanitizedQuery'
     */
    @Test
    public void sanitizedQueryTest() {
        // TODO: test sanitizedQuery
    }

}
