/*
 * The Jira Cloud platform REST API
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT-9aad01a33a3dae75a5b6aedf98c77d2cbd2f865d
 * Contact: ecosystem@atlassian.com
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.DocumentVersion;
import com.konfigthis.client.model.WorkflowMetadataAndIssueTypeRestModel;
import com.konfigthis.client.model.WorkflowMetadataRestModel;
import com.konfigthis.client.model.WorkflowScope;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for WorkflowSchemeReadResponse
 */
public class WorkflowSchemeReadResponseTest {
    private final WorkflowSchemeReadResponse model = new WorkflowSchemeReadResponse();

    /**
     * Model tests for WorkflowSchemeReadResponse
     */
    @Test
    public void testWorkflowSchemeReadResponse() {
        // TODO: test WorkflowSchemeReadResponse
    }

    /**
     * Test the property 'description'
     */
    @Test
    public void descriptionTest() {
        // TODO: test description
    }

    /**
     * Test the property 'version'
     */
    @Test
    public void versionTest() {
        // TODO: test version
    }

    /**
     * Test the property 'defaultWorkflow'
     */
    @Test
    public void defaultWorkflowTest() {
        // TODO: test defaultWorkflow
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'projectIdsUsingScheme'
     */
    @Test
    public void projectIdsUsingSchemeTest() {
        // TODO: test projectIdsUsingScheme
    }

    /**
     * Test the property 'scope'
     */
    @Test
    public void scopeTest() {
        // TODO: test scope
    }

    /**
     * Test the property 'taskId'
     */
    @Test
    public void taskIdTest() {
        // TODO: test taskId
    }

    /**
     * Test the property 'workflowsForIssueTypes'
     */
    @Test
    public void workflowsForIssueTypesTest() {
        // TODO: test workflowsForIssueTypes
    }

}
