/*
 * The Jira Cloud platform REST API
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT-9aad01a33a3dae75a5b6aedf98c77d2cbd2f865d
 * Contact: ecosystem@atlassian.com
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.DateRangeFilterRequest;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import org.apache.commons.lang3.StringUtils;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import com.konfigthis.client.JSON;

/**
 * Details of a filter for exporting archived issues.
 */
@ApiModel(description = "Details of a filter for exporting archived issues.")@javax.annotation.Generated(value = "Generated by https://konfigthis.com")
public class ArchivedIssuesFilterRequest {
  public static final String SERIALIZED_NAME_ARCHIVED_BY = "archivedBy";
  @SerializedName(SERIALIZED_NAME_ARCHIVED_BY)
  private List<String> archivedBy = null;

  public static final String SERIALIZED_NAME_ARCHIVED_DATE_RANGE = "archivedDateRange";
  @SerializedName(SERIALIZED_NAME_ARCHIVED_DATE_RANGE)
  private DateRangeFilterRequest archivedDateRange;

  public static final String SERIALIZED_NAME_ISSUE_TYPES = "issueTypes";
  @SerializedName(SERIALIZED_NAME_ISSUE_TYPES)
  private List<String> issueTypes = null;

  public static final String SERIALIZED_NAME_PROJECTS = "projects";
  @SerializedName(SERIALIZED_NAME_PROJECTS)
  private List<String> projects = null;

  public static final String SERIALIZED_NAME_REPORTERS = "reporters";
  @SerializedName(SERIALIZED_NAME_REPORTERS)
  private List<String> reporters = null;

  public ArchivedIssuesFilterRequest() {
  }

  public ArchivedIssuesFilterRequest archivedBy(List<String> archivedBy) {
    
    
    
    
    this.archivedBy = archivedBy;
    return this;
  }

  public ArchivedIssuesFilterRequest addArchivedByItem(String archivedByItem) {
    if (this.archivedBy == null) {
      this.archivedBy = new ArrayList<>();
    }
    this.archivedBy.add(archivedByItem);
    return this;
  }

   /**
   * List archived issues archived by a specified account ID.
   * @return archivedBy
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "List archived issues archived by a specified account ID.")

  public List<String> getArchivedBy() {
    return archivedBy;
  }


  public void setArchivedBy(List<String> archivedBy) {
    
    
    
    this.archivedBy = archivedBy;
  }


  public ArchivedIssuesFilterRequest archivedDateRange(DateRangeFilterRequest archivedDateRange) {
    
    
    
    
    this.archivedDateRange = archivedDateRange;
    return this;
  }

   /**
   * Get archivedDateRange
   * @return archivedDateRange
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public DateRangeFilterRequest getArchivedDateRange() {
    return archivedDateRange;
  }


  public void setArchivedDateRange(DateRangeFilterRequest archivedDateRange) {
    
    
    
    this.archivedDateRange = archivedDateRange;
  }


  public ArchivedIssuesFilterRequest issueTypes(List<String> issueTypes) {
    
    
    
    
    this.issueTypes = issueTypes;
    return this;
  }

  public ArchivedIssuesFilterRequest addIssueTypesItem(String issueTypesItem) {
    if (this.issueTypes == null) {
      this.issueTypes = new ArrayList<>();
    }
    this.issueTypes.add(issueTypesItem);
    return this;
  }

   /**
   * List archived issues with a specified issue type ID.
   * @return issueTypes
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "List archived issues with a specified issue type ID.")

  public List<String> getIssueTypes() {
    return issueTypes;
  }


  public void setIssueTypes(List<String> issueTypes) {
    
    
    
    this.issueTypes = issueTypes;
  }


  public ArchivedIssuesFilterRequest projects(List<String> projects) {
    
    
    
    
    this.projects = projects;
    return this;
  }

  public ArchivedIssuesFilterRequest addProjectsItem(String projectsItem) {
    if (this.projects == null) {
      this.projects = new ArrayList<>();
    }
    this.projects.add(projectsItem);
    return this;
  }

   /**
   * List archived issues with a specified project key.
   * @return projects
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "List archived issues with a specified project key.")

  public List<String> getProjects() {
    return projects;
  }


  public void setProjects(List<String> projects) {
    
    
    
    this.projects = projects;
  }


  public ArchivedIssuesFilterRequest reporters(List<String> reporters) {
    
    
    
    
    this.reporters = reporters;
    return this;
  }

  public ArchivedIssuesFilterRequest addReportersItem(String reportersItem) {
    if (this.reporters == null) {
      this.reporters = new ArrayList<>();
    }
    this.reporters.add(reportersItem);
    return this;
  }

   /**
   * List archived issues where the reporter is a specified account ID.
   * @return reporters
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "List archived issues where the reporter is a specified account ID.")

  public List<String> getReporters() {
    return reporters;
  }


  public void setReporters(List<String> reporters) {
    
    
    
    this.reporters = reporters;
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the ArchivedIssuesFilterRequest instance itself
   */
  public ArchivedIssuesFilterRequest putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ArchivedIssuesFilterRequest archivedIssuesFilterRequest = (ArchivedIssuesFilterRequest) o;
    return Objects.equals(this.archivedBy, archivedIssuesFilterRequest.archivedBy) &&
        Objects.equals(this.archivedDateRange, archivedIssuesFilterRequest.archivedDateRange) &&
        Objects.equals(this.issueTypes, archivedIssuesFilterRequest.issueTypes) &&
        Objects.equals(this.projects, archivedIssuesFilterRequest.projects) &&
        Objects.equals(this.reporters, archivedIssuesFilterRequest.reporters)&&
        Objects.equals(this.additionalProperties, archivedIssuesFilterRequest.additionalProperties);
  }

  @Override
  public int hashCode() {
    return Objects.hash(archivedBy, archivedDateRange, issueTypes, projects, reporters, additionalProperties);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ArchivedIssuesFilterRequest {\n");
    sb.append("    archivedBy: ").append(toIndentedString(archivedBy)).append("\n");
    sb.append("    archivedDateRange: ").append(toIndentedString(archivedDateRange)).append("\n");
    sb.append("    issueTypes: ").append(toIndentedString(issueTypes)).append("\n");
    sb.append("    projects: ").append(toIndentedString(projects)).append("\n");
    sb.append("    reporters: ").append(toIndentedString(reporters)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("archivedBy");
    openapiFields.add("archivedDateRange");
    openapiFields.add("issueTypes");
    openapiFields.add("projects");
    openapiFields.add("reporters");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to ArchivedIssuesFilterRequest
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (!ArchivedIssuesFilterRequest.openapiRequiredFields.isEmpty()) { // has required fields but JSON object is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in ArchivedIssuesFilterRequest is not found in the empty JSON string", ArchivedIssuesFilterRequest.openapiRequiredFields.toString()));
        }
      }
      // ensure the optional json data is an array if present
      if (jsonObj.get("archivedBy") != null && !jsonObj.get("archivedBy").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `archivedBy` to be an array in the JSON string but got `%s`", jsonObj.get("archivedBy").toString()));
      }
      // validate the optional field `archivedDateRange`
      if (jsonObj.get("archivedDateRange") != null && !jsonObj.get("archivedDateRange").isJsonNull()) {
        DateRangeFilterRequest.validateJsonObject(jsonObj.getAsJsonObject("archivedDateRange"));
      }
      // ensure the optional json data is an array if present
      if (jsonObj.get("issueTypes") != null && !jsonObj.get("issueTypes").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `issueTypes` to be an array in the JSON string but got `%s`", jsonObj.get("issueTypes").toString()));
      }
      // ensure the optional json data is an array if present
      if (jsonObj.get("projects") != null && !jsonObj.get("projects").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `projects` to be an array in the JSON string but got `%s`", jsonObj.get("projects").toString()));
      }
      // ensure the optional json data is an array if present
      if (jsonObj.get("reporters") != null && !jsonObj.get("reporters").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `reporters` to be an array in the JSON string but got `%s`", jsonObj.get("reporters").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!ArchivedIssuesFilterRequest.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'ArchivedIssuesFilterRequest' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<ArchivedIssuesFilterRequest> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(ArchivedIssuesFilterRequest.class));

       return (TypeAdapter<T>) new TypeAdapter<ArchivedIssuesFilterRequest>() {
           @Override
           public void write(JsonWriter out, ArchivedIssuesFilterRequest value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             obj.remove("additionalProperties");
             // serialize additonal properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   obj.add(entry.getKey(), gson.toJsonTree(entry.getValue()).getAsJsonObject());
                 }
               }
             }
             elementAdapter.write(out, obj);
           }

           @Override
           public ArchivedIssuesFilterRequest read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             // store additional fields in the deserialized instance
             ArchivedIssuesFilterRequest instance = thisAdapter.fromJsonTree(jsonObj);
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format("The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else if (entry.getValue().isJsonArray()) {
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), List.class));
                 } else { // JSON object
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of ArchivedIssuesFilterRequest given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of ArchivedIssuesFilterRequest
  * @throws IOException if the JSON string is invalid with respect to ArchivedIssuesFilterRequest
  */
  public static ArchivedIssuesFilterRequest fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, ArchivedIssuesFilterRequest.class);
  }

 /**
  * Convert an instance of ArchivedIssuesFilterRequest to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

