/*
 * The Jira Cloud platform REST API
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT-9aad01a33a3dae75a5b6aedf98c77d2cbd2f865d
 * Contact: ecosystem@atlassian.com
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.JiraExpressionsComplexityValueBean;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import org.apache.commons.lang3.StringUtils;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import com.konfigthis.client.JSON;

/**
 * JiraExpressionsComplexityBean
 */@javax.annotation.Generated(value = "Generated by https://konfigthis.com")
public class JiraExpressionsComplexityBean {
  public static final String SERIALIZED_NAME_BEANS = "beans";
  @SerializedName(SERIALIZED_NAME_BEANS)
  private JiraExpressionsComplexityValueBean beans;

  public static final String SERIALIZED_NAME_EXPENSIVE_OPERATIONS = "expensiveOperations";
  @SerializedName(SERIALIZED_NAME_EXPENSIVE_OPERATIONS)
  private JiraExpressionsComplexityValueBean expensiveOperations;

  public static final String SERIALIZED_NAME_PRIMITIVE_VALUES = "primitiveValues";
  @SerializedName(SERIALIZED_NAME_PRIMITIVE_VALUES)
  private JiraExpressionsComplexityValueBean primitiveValues;

  public static final String SERIALIZED_NAME_STEPS = "steps";
  @SerializedName(SERIALIZED_NAME_STEPS)
  private JiraExpressionsComplexityValueBean steps;

  public JiraExpressionsComplexityBean() {
  }

  public JiraExpressionsComplexityBean beans(JiraExpressionsComplexityValueBean beans) {
    
    
    
    
    this.beans = beans;
    return this;
  }

   /**
   * The number of Jira REST API beans returned in the response.
   * @return beans
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "The number of Jira REST API beans returned in the response.")

  public JiraExpressionsComplexityValueBean getBeans() {
    return beans;
  }


  public void setBeans(JiraExpressionsComplexityValueBean beans) {
    
    
    
    this.beans = beans;
  }


  public JiraExpressionsComplexityBean expensiveOperations(JiraExpressionsComplexityValueBean expensiveOperations) {
    
    
    
    
    this.expensiveOperations = expensiveOperations;
    return this;
  }

   /**
   * The number of expensive operations executed while evaluating the expression. Expensive operations are those that load additional data, such as entity properties, comments, or custom fields.
   * @return expensiveOperations
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "The number of expensive operations executed while evaluating the expression. Expensive operations are those that load additional data, such as entity properties, comments, or custom fields.")

  public JiraExpressionsComplexityValueBean getExpensiveOperations() {
    return expensiveOperations;
  }


  public void setExpensiveOperations(JiraExpressionsComplexityValueBean expensiveOperations) {
    
    
    
    this.expensiveOperations = expensiveOperations;
  }


  public JiraExpressionsComplexityBean primitiveValues(JiraExpressionsComplexityValueBean primitiveValues) {
    
    
    
    
    this.primitiveValues = primitiveValues;
    return this;
  }

   /**
   * The number of primitive values returned in the response.
   * @return primitiveValues
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "The number of primitive values returned in the response.")

  public JiraExpressionsComplexityValueBean getPrimitiveValues() {
    return primitiveValues;
  }


  public void setPrimitiveValues(JiraExpressionsComplexityValueBean primitiveValues) {
    
    
    
    this.primitiveValues = primitiveValues;
  }


  public JiraExpressionsComplexityBean steps(JiraExpressionsComplexityValueBean steps) {
    
    
    
    
    this.steps = steps;
    return this;
  }

   /**
   * The number of steps it took to evaluate the expression, where a step is a high-level operation performed by the expression. A step is an operation such as arithmetic, accessing a property, accessing a context variable, or calling a function.
   * @return steps
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "The number of steps it took to evaluate the expression, where a step is a high-level operation performed by the expression. A step is an operation such as arithmetic, accessing a property, accessing a context variable, or calling a function.")

  public JiraExpressionsComplexityValueBean getSteps() {
    return steps;
  }


  public void setSteps(JiraExpressionsComplexityValueBean steps) {
    
    
    
    this.steps = steps;
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the JiraExpressionsComplexityBean instance itself
   */
  public JiraExpressionsComplexityBean putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    JiraExpressionsComplexityBean jiraExpressionsComplexityBean = (JiraExpressionsComplexityBean) o;
    return Objects.equals(this.beans, jiraExpressionsComplexityBean.beans) &&
        Objects.equals(this.expensiveOperations, jiraExpressionsComplexityBean.expensiveOperations) &&
        Objects.equals(this.primitiveValues, jiraExpressionsComplexityBean.primitiveValues) &&
        Objects.equals(this.steps, jiraExpressionsComplexityBean.steps)&&
        Objects.equals(this.additionalProperties, jiraExpressionsComplexityBean.additionalProperties);
  }

  @Override
  public int hashCode() {
    return Objects.hash(beans, expensiveOperations, primitiveValues, steps, additionalProperties);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class JiraExpressionsComplexityBean {\n");
    sb.append("    beans: ").append(toIndentedString(beans)).append("\n");
    sb.append("    expensiveOperations: ").append(toIndentedString(expensiveOperations)).append("\n");
    sb.append("    primitiveValues: ").append(toIndentedString(primitiveValues)).append("\n");
    sb.append("    steps: ").append(toIndentedString(steps)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("beans");
    openapiFields.add("expensiveOperations");
    openapiFields.add("primitiveValues");
    openapiFields.add("steps");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("beans");
    openapiRequiredFields.add("expensiveOperations");
    openapiRequiredFields.add("primitiveValues");
    openapiRequiredFields.add("steps");
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to JiraExpressionsComplexityBean
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (!JiraExpressionsComplexityBean.openapiRequiredFields.isEmpty()) { // has required fields but JSON object is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in JiraExpressionsComplexityBean is not found in the empty JSON string", JiraExpressionsComplexityBean.openapiRequiredFields.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : JiraExpressionsComplexityBean.openapiRequiredFields) {
        if (jsonObj.get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonObj.toString()));
        }
      }
      // validate the required field `beans`
      JiraExpressionsComplexityValueBean.validateJsonObject(jsonObj.getAsJsonObject("beans"));
      // validate the required field `expensiveOperations`
      JiraExpressionsComplexityValueBean.validateJsonObject(jsonObj.getAsJsonObject("expensiveOperations"));
      // validate the required field `primitiveValues`
      JiraExpressionsComplexityValueBean.validateJsonObject(jsonObj.getAsJsonObject("primitiveValues"));
      // validate the required field `steps`
      JiraExpressionsComplexityValueBean.validateJsonObject(jsonObj.getAsJsonObject("steps"));
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!JiraExpressionsComplexityBean.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'JiraExpressionsComplexityBean' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<JiraExpressionsComplexityBean> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(JiraExpressionsComplexityBean.class));

       return (TypeAdapter<T>) new TypeAdapter<JiraExpressionsComplexityBean>() {
           @Override
           public void write(JsonWriter out, JiraExpressionsComplexityBean value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             obj.remove("additionalProperties");
             // serialize additonal properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   obj.add(entry.getKey(), gson.toJsonTree(entry.getValue()).getAsJsonObject());
                 }
               }
             }
             elementAdapter.write(out, obj);
           }

           @Override
           public JiraExpressionsComplexityBean read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             // store additional fields in the deserialized instance
             JiraExpressionsComplexityBean instance = thisAdapter.fromJsonTree(jsonObj);
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format("The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else if (entry.getValue().isJsonArray()) {
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), List.class));
                 } else { // JSON object
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of JiraExpressionsComplexityBean given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of JiraExpressionsComplexityBean
  * @throws IOException if the JSON string is invalid with respect to JiraExpressionsComplexityBean
  */
  public static JiraExpressionsComplexityBean fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, JiraExpressionsComplexityBean.class);
  }

 /**
  * Convert an instance of JiraExpressionsComplexityBean to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

