/*
 * The Jira Cloud platform REST API
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT-9aad01a33a3dae75a5b6aedf98c77d2cbd2f865d
 * Contact: ecosystem@atlassian.com
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.api;

import com.konfigthis.client.ApiException;
import com.konfigthis.client.ApiClient;
import com.konfigthis.client.ApiException;
import com.konfigthis.client.Configuration;
import com.konfigthis.client.model.ProjectDataPolicies;
import com.konfigthis.client.model.WorkspaceDataPolicy;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.BeforeAll;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for AppDataPoliciesEapApi
 */
@Disabled
public class AppDataPoliciesEapApiTest {

    private static AppDataPoliciesEapApi api;

    
    @BeforeAll
    public static void beforeClass() {
        ApiClient apiClient = Configuration.getDefaultApiClient();
        api = new AppDataPoliciesEapApi(apiClient);
    }

    /**
     * Get data policy for projects (EAP)
     *
     * Returns data policies for the projects specified in the request.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getDataPolicyProjectsTest() throws ApiException {
        String ids = null;
        ProjectDataPolicies response = api.getDataPolicyProjects()
                .ids(ids)
                .execute();
        // TODO: test validations
    }

    /**
     * Get data policy for the workspace (EAP)
     *
     * Returns data policy for the workspace.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getDataPolicyWorkspaceTest() throws ApiException {
        WorkspaceDataPolicy response = api.getDataPolicyWorkspace()
                .execute();
        // TODO: test validations
    }

}
